name: Windows

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.12.10]
        qt_target: [desktop]
        qt_arch: [win64_msvc2017_64,win32_msvc2017]
        include:
          - qt_arch: win64_msvc2017_64
            msvc_arch: x64
            qt_arch_install: msvc2017_64
          - qt_arch: win32_msvc2017
            msvc_arch: x86
            qt_arch_install: msvc2017

    steps:
    - name: cacheQt
      id: WindowsCacheQt
      uses: actions/cache@v1
      with:
        path: ../Qt/${{ matrix.qt_ver }}/${{ matrix.qt_arch_install }}
        key: ${{ runner.os }}-Qt/${{ matrix.qt_ver }}/${{ matrix.qt_arch }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_ver }}
        target: ${{ matrix.qt_target }}
        arch: ${{ matrix.qt_arch }}
        cached: ${{ steps.WindowsCacheQt.outputs.cache-hit }}

    - uses: actions/checkout@v2

    - name: build-msvc
      shell: cmd
      env:
        vc_arch: ${{ matrix.msvc_arch }}
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
        qmake
        jom
